FROM ubuntu:latest
WORKDIR /app
ADD src/s3sync/crontab /etc/cron.d/hello-cron
RUN chmod 0644 /etc/cron.d/hello-cron
RUN touch /var/log/cron.log
RUN apt-get update
RUN apt-get -y install cron
RUN apt install awscli -y
COPY scripts/login_sync_s3.sh ./login_sync_s3.sh
COPY ./.env ./.env
CMD cron && tail -f /var/log/cron.log
