import chai from "chai";
import chaiHttp from "chai-http";
import {
  deployFromBytecodeForCreatorTxHash,
  hookIntoVerificationWorkerRun,
} from "../../helpers/helpers";
import { LocalChainFixture } from "../../helpers/LocalChainFixture";
import { ServerFixture } from "../../helpers/ServerFixture";
import type {
  AnyJsonInput,
  Metadata,
  Transformation,
  TransformationValues,
} from "@ethereum-sourcify/lib-sourcify";
import type { Tables } from "../../../src/server/services/utils/database-util";
import type { MatchLevel } from "../../../src/server/types";
import sinon from "sinon";
import { assertApiV2Lookup, assertDatabase } from "./assertions";

chai.use(chaiHttp);

export interface VerificationTestCase {
  /*
   * The bytecodes as they would appear onchain.
   * When creating a test case, it is important to ensure that these are exactly
   * how they would appear onchain and are not simply taken from the compiler
   * output. Notably the onchain code and the compiler output differs in these
   * ways (transformations):
   * - libraries must be linked in onchain code
   * - creationBytecode should have constructor arguments appended
   * - deployedBytecode includes immutables
   * - For library contracts: deployedBytecode should have the call protection
   *    placeholder replaced
   */
  onchain: {
    creationBytecode: string;
    deployedBytecode: string;
  };
  /*
   * The input used to send to API v2 for verification.
   * This is an object such that other API input types (e.g., metadata) can be
   * added in the future.
   */
  input: {
    stdJsonInput: AnyJsonInput;
    compilerVersion: string;
    contractIdentifier: string;
  };
  /*
   * The output from the compiler in the format as we store it in the database.
   * It should be generated from compiling exactly the input above.
   */
  output: {
    creationBytecode: string;
    deployedBytecode: string;
    compilationArtifacts: Tables.CompiledContract["compilation_artifacts"];
    creationCodeArtifacts: Tables.CompiledContract["creation_code_artifacts"];
    runtimeCodeArtifacts: Tables.CompiledContract["runtime_code_artifacts"];
    metadata: Metadata | undefined;
  };
  /*
   * The verification object includes any fields that are generated by
   * ourselves during verification (i.e., not by the compiler) and are stored
   * in the database.
   */
  verification: {
    creationMatch: MatchLevel;
    runtimeMatch: MatchLevel;
    creationTransformations: Transformation[];
    creationValues: TransformationValues;
    runtimeTransformations: Transformation[];
    runtimeValues: TransformationValues;
  };
}

/*
 * This suite aims to provide a uniform way to test that specific edge cases
 * are verified and stored correctly in Sourcify. For example, this includes
 * that transformations are generated correctly and that contracts can still
 * be verified when certain compiler settings are changed. At the moment, it
 * tests for correct storage via querying the database directly and checking
 * the response of API v2. It is meant to be extensible for testing storage
 * on other storage services as well.
 *
 * Each test case takes an object in the form of the VerificationTestCase
 * interface as input. The logic deploys the contract on a local chain and
 * verifies it using API v2. After the verification is complete, it queries
 * and checks all relevant database columns and the API v2
 * /contract/{chainId}/{address} endpoint.
 */
describe("Specific Verification Cases", function () {
  // Historical Vyper cases may cold-install an exact Python/compiler runtime
  // before the worker's own five-minute process timeout begins.
  this.timeout(10 * 60 * 1000);
  const chainFixture = new LocalChainFixture();
  const serverFixture = new ServerFixture();
  const sandbox = sinon.createSandbox();
  const makeWorkersWait = hookIntoVerificationWorkerRun(sandbox, serverFixture);

  afterEach(async () => {
    sandbox.restore();
  });

  const testVerificationCase = async (testCase: VerificationTestCase) => {
    const { resolveWorkers } = makeWorkersWait();
    const deploymentInfo = await deployFromBytecodeForCreatorTxHash(
      chainFixture.localSigner,
      testCase.onchain.creationBytecode,
    );

    const verifyRes = await chai
      .request(serverFixture.server.app)
      .post(
        `/v2/verify/${chainFixture.chainId}/${deploymentInfo.contractAddress}`,
      )
      .send({
        contractIdentifier: testCase.input.contractIdentifier,
        creationTransactionHash: deploymentInfo.txHash,
        stdJsonInput: testCase.input.stdJsonInput,
        compilerVersion: testCase.input.compilerVersion,
      });

    chai.expect(verifyRes.status).to.equal(202);
    await resolveWorkers();

    await assertDatabase(
      serverFixture,
      testCase,
      chainFixture.chainId,
      chainFixture.localSigner.address,
      deploymentInfo,
    );

    await assertApiV2Lookup(
      serverFixture,
      testCase,
      chainFixture.chainId,
      chainFixture.localSigner.address,
      deploymentInfo,
    );
  };

  it("Libraries have been linked manually instead of using compiler settings. Placeholders are replaced with zero addresses", async () => {
    const verifierAllianceTestLibrariesManuallyLinked = (
      await import("./testdata/libraries_manually_linked.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(verifierAllianceTestLibrariesManuallyLinked);
  });

  it("Store full match in database", async () => {
    const verifierAllianceTestFullMatch = (
      await import("./testdata/full_match.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(verifierAllianceTestFullMatch);
  });

  it("Store match with immutables in sourcify database", async () => {
    const verifierAllianceTestImmutables = (
      await import("./testdata/immutables.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(verifierAllianceTestImmutables);
  });

  it("Libraries have been linked using compiler settings. The placeholders are already replaced inside the compiled bytecode, and no link references provided", async () => {
    const verifierAllianceTestLibrariesLinkedByCompiler = (
      await import("./testdata/libraries_linked_by_compiler.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(verifierAllianceTestLibrariesLinkedByCompiler);
  });

  it("Store match without auxdata in database", async () => {
    const verifierAllianceTestMetadataHashAbsent = (
      await import("./testdata/metadata_hash_absent.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(verifierAllianceTestMetadataHashAbsent);
  });

  it("Store partial match in database", async () => {
    const verifierAllianceTestPartialMatch = (
      await import("./testdata/partial_match.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(verifierAllianceTestPartialMatch);
  });

  it("Store match deployed with constructor arguments in database", async () => {
    const verifierAllianceTestConstructorArguments = (
      await import("./testdata/constructor_arguments.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(verifierAllianceTestConstructorArguments);
  });

  it("Store partial match in database for a contract with multiple auxdatas", async () => {
    const verifierAllianceTestDoubleAuxdata = (
      await import("./testdata/partial_match_double_auxdata.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(verifierAllianceTestDoubleAuxdata);
  });

  it("Store full match in the database for a contract with multiple auxdatas", async () => {
    const verifierAllianceTestDoubleAuxdata = (
      await import("./testdata/full_match_double_auxdata.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(verifierAllianceTestDoubleAuxdata);
  });

  it("Store Yul match in the database", async () => {
    const verifierAllianceTestYulMatch = (await import("./testdata/yul.json"))
      .default as unknown as VerificationTestCase;
    await testVerificationCase(verifierAllianceTestYulMatch);
  });

  it("Store a partial match in the database when a parameter name was changed", async () => {
    const verifierAllianceTestPartialMatch2 = (
      await import("./testdata/partial_match_2.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(verifierAllianceTestPartialMatch2);
  });

  it("should verify a Vyper 0.1.0-beta.16 contract (no CBOR auxdata)", async () => {
    const vyperTestNoAuxdata0_1_0_beta_16 = (
      await import("./testdata/vyper/no-auxdata-0.1.0-beta.16.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestNoAuxdata0_1_0_beta_16);
  });

  it("should verify a Vyper 0.2.0 contract (no CBOR auxdata)", async () => {
    const vyperTestNoAuxdata0_2_0 = (
      await import("./testdata/vyper/no-auxdata-0.2.0.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestNoAuxdata0_2_0);
  });

  it("should verify a Vyper 0.3.3 contract (no CBOR auxdata)", async () => {
    const vyperTestNoAuxdata0_3_3 = (
      await import("./testdata/vyper/no-auxdata-0.3.3.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestNoAuxdata0_3_3);
  });

  it("should store auxdata for a Vyper contract compiled with 0.3.4", async () => {
    const vyperTestAuxdata0_3_4 = (
      await import("./testdata/vyper/auxdata-0.3.4.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestAuxdata0_3_4);
  });

  it("should store a partial match for a Vyper 0.3.4 contract where the onchain cbor auxdata has a different version", async () => {
    const vyperTestAuxdata0_3_4DifferentVersion = (
      await import("./testdata/vyper/auxdata-0.3.4-different-version.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestAuxdata0_3_4DifferentVersion);
  });

  it("should store auxdata for a Vyper contract compiled with 0.3.8", async () => {
    const vyperTestAuxdata0_3_8 = (
      await import("./testdata/vyper/auxdata-0.3.8.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestAuxdata0_3_8);
  });

  it("should store a partial match for a Vyper 0.3.8 contract where the onchain cbor auxdata has a different version", async () => {
    const vyperTestAuxdata0_3_8DifferentVersion = (
      await import("./testdata/vyper/auxdata-0.3.8-different-version.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestAuxdata0_3_8DifferentVersion);
  });

  it("should store auxdata for a Vyper contract compiled with 0.4.0", async () => {
    const vyperTestAuxdata0_4_0 = (
      await import("./testdata/vyper/auxdata-0.4.0.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestAuxdata0_4_0);
  });

  it("should store auxdata for a Vyper contract compiled with 0.4.1", async () => {
    const vyperTestAuxdata0_4_1 = (
      await import("./testdata/vyper/auxdata-0.4.1.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestAuxdata0_4_1);
  });

  it("should store a partial match for a Vyper 0.4.1 contract where the integrity hash differs", async () => {
    const vyperTestAuxdata0_4_1DifferentIntegrity = (
      await import("./testdata/vyper/auxdata-0.4.1-different-integrity.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestAuxdata0_4_1DifferentIntegrity);
  });

  it("should store transformations for a Vyper contract with constructor arguments and immutables", async () => {
    const vyperTestConstructorArgumentsAndImmutables = (
      await import("./testdata/vyper/constructor_args_immutables.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestConstructorArgumentsAndImmutables);
  });

  it("should partially match when deployed bytecodeHash none is verified with standard metadata", async () => {
    const vyperTestConstructorArgumentsAndImmutables = (
      await import("./testdata/onchain_bytecode_hash_none_compiled_standard.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestConstructorArgumentsAndImmutables);
  });

  it("should partially match when deployed appendCBOR false is verified with standard metadata", async () => {
    const vyperTestConstructorArgumentsAndImmutables = (
      await import("./testdata/onchain_append_cbor_false_compiled_standard.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestConstructorArgumentsAndImmutables);
  });

  it("should partially match when deployed appendCBOR false is verified with metadata bytecodeHash none", async () => {
    const vyperTestConstructorArgumentsAndImmutables = (
      await import("./testdata/onchain_append_cbor_false_compiled_bytecode_hash_none.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestConstructorArgumentsAndImmutables);
  });

  it("should verify a Vyper contract with storage_layout_overrides", async () => {
    const vyperTestStorageLayoutOverrides = (
      await import("./testdata/vyper/storage_layout_overrides.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(vyperTestStorageLayoutOverrides);
  });

  it("should partially match a contract compiled with Solidity 0.1.3", async () => {
    const matchSol0_1_3 = (await import("./testdata/match_sol_0_1_3.json"))
      .default as unknown as VerificationTestCase;
    await testVerificationCase(matchSol0_1_3);
  });

  it("should partially match a contract compiled with Solidity 0.1.6", async () => {
    const matchSol0_1_6 = (await import("./testdata/match_sol_0_1_6.json"))
      .default as unknown as VerificationTestCase;
    await testVerificationCase(matchSol0_1_6);
  });

  it("should partially match a contract compiled with Solidity 0.3.6", async () => {
    const matchSol0_3_6 = (await import("./testdata/match_sol_0_3_6.json"))
      .default as unknown as VerificationTestCase;
    await testVerificationCase(matchSol0_3_6);
  });

  it("should partially match a contract compiled with Solidity 0.4.0", async () => {
    const matchSol0_4_0 = (await import("./testdata/match_sol_0_4_0.json"))
      .default as unknown as VerificationTestCase;
    await testVerificationCase(matchSol0_4_0);
  });

  it("should partially match a contract compiled with Solidity 0.4.7", async () => {
    const matchSol0_4_7 = (await import("./testdata/match_sol_0_4_7.json"))
      .default as unknown as VerificationTestCase;
    await testVerificationCase(matchSol0_4_7);
  });

  it("should partially match a contract compiled with Solidity 0.4.9", async () => {
    const matchSol0_4_9 = (await import("./testdata/match_sol_0_4_9.json"))
      .default as unknown as VerificationTestCase;
    await testVerificationCase(matchSol0_4_9);
  });

  it("should store transientStorageLayout for a contract that uses the transient keyword", async () => {
    const transientStorageLayout = (
      await import("./testdata/transient_storage_layout.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(transientStorageLayout);
  });

  it("should verify a multi-source Solidity contract without duplicating signatures", async () => {
    const multiSourceSolidity = (
      await import("./testdata/multi_source_solidity.json")
    ).default as unknown as VerificationTestCase;
    await testVerificationCase(multiSourceSolidity);
  });

  it("should verify a single-file Fe contract", async () => {
    const feTestSingleFile = (await import("./testdata/fe/single_file.json"))
      .default as unknown as VerificationTestCase;
    await testVerificationCase(feTestSingleFile);
  });

  it("should verify a multi-file Fe ingot", async () => {
    const feTestMultiFile = (await import("./testdata/fe/multi_file.json"))
      .default as unknown as VerificationTestCase;
    await testVerificationCase(feTestMultiFile);
  });
});
