version: "3.7"
services:
  https-portal:
    container_name: https-portal-${TAG}
    image: steveltn/https-portal:latest
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - server
      - ui
      - repository
    environment:
      DOMAINS: 'server.${FQDN} -> http://server-${TAG}:${SERVER_PORT}, ${FQDN} -> http://ui-${TAG}:${UI_PORT}, contractrepo.${FQDN} -> http://repository-${TAG}:${REPOSITORY_PORT}, prometheus.${FQDN} -> http://prometheus:9090, grafana.${FQDN} -> http://grafana:11000, loki.${FQDN} -> http://loki:3100'
      STAGE: 'local'
      FORCE_RENEW: 'false'
    networks:
    - source-verify

networks:
  source-verify:

