version: "3.7"
x-project-repository-mount:
  &project-repository-mount
  type: bind
  source: $REPOSITORY_PATH

x-project-database-mount:
  &project-database-mount
  type: bind
  source: $DATABASE_PATH

x-project-base:
  &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

networks:
  source-verify:
  
services:
  ipfs:
    <<: *project-base
    image: ethereum/source-verify:ipfs-${TAG}
    container_name: ipfs-${TAG}
    volumes:
    - <<: *project-database-mount
      target: /app/repository/repository/
    - <<: *project-repository-mount
      target: /app/repository/database/
     
