version: "3.7"
x-project-repository-mount:
  &project-repository-mount
  type: bind
  source: $REPOSITORY_PATH

x-project-base:
  &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

networks:
  source-verify:

services:
  monitor:
    <<: *project-base
    image: ethereum/source-verify:monitor-${TAG}
    container_name: monitor-${TAG}
    volumes:
      - <<: *project-repository-mount
        target: /home/data/repository
      - type: bind
        source: $SOLC_REPO_HOST
        target: $SOLC_REPO
        read_only: true
    ports:
    - "${MONITOR_EXTERNAL_PORT}:${MONITOR_PORT}"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g
