version: "3.7"

networks:
  source-verify:

x-project-base: &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

services:
  ui:
    <<: *project-base
    image: ethereum/source-verify:ui-${TAG}
    container_name: ui-${TAG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - "${UI_EXTERNAL_PORT}:80"
