FROM ubuntu:18.04
WORKDIR /app
RUN apt-get update && apt-get install -y cron curl unzip
RUN curl https://dist.ipfs.io/go-ipfs/v0.4.23/go-ipfs_v0.4.23_linux-amd64.tar.gz > go-ipfs.tar.gz && tar xvfz go-ipfs.tar.gz && cd go-ipfs && ./install.sh
ADD src/ipfs/publish_to_ipfs.sh ./publish_to_ipfs.sh
ADD src/ipfs/entrypoint.sh ./entrypoint.sh
COPY ./environments/.env .env
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ./entrypoint.sh
