openapi: "3.0.0"

paths:
  /files/contracts/any/{chain}:
    get:
      deprecated: true
      summary: Get the contract addresses verified on a chain (full or partial match)
      description: Returns the verified contracts from the repository for the desired chain. Searches for full and partial matches. API is paginated. Limit must be a number between 1 and 200.
      tags:
        - (Deprecated) Repository
      parameters:
        - name: chain
          in: path
          required: true
          schema:
            type: string
            format: sourcify-chainId
        - name: page
          in: query
          required: false
          schema:
            type: number
        - name: limit
          in: query
          required: false
          schema:
            type: number
            minimum: 1
            maximum: 200
        - name: order
          in: query
          required: false
          schema:
            type: string
            enum: [asc, desc]
          description: Order of the results. Default is "asc" (earliest verified contract first)
      responses:
        "200":
          description: Chain is available as a full match or partial match in the repository
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: string
                    example:
                      [
                        "0x1fE5d745beABA808AAdF52057Dd7AAA47b42cFD0",
                        "0xE9c31091868d68598Ac881738D159A63532d12f9",
                      ]
                  pagination:
                    type: object
                    properties:
                      currentPage:
                        type: number
                      totalPages:
                        type: number
                      resultsPerPage:
                        type: number
                      resultsCurrentPage:
                        type: number
                      totalResults:
                        type: number
                      hasNextPage:
                        type: boolean
                      hasPreviousPage:
                        type: boolean
