#!/bin/bash
set -e

source ~/.profile

cd scripts/
gpg --yes --batch --passphrase=$SECRET_KEY ../environments/.env.secrets.gpg
gpg --yes --batch --passphrase=$SECRET_KEY ../services/ipfs/ipfs-stable.key.gpg
gpg --yes --batch --passphrase=$SECRET_KEY ../services/ipfs/ipfs-latest.key.gpg
source ../environments/.env.secrets

TAG="$CIRCLE_BRANCH"

if [ "$CIRCLE_BRANCH" == "staging" ]; then
    TAG="latest"
    INFURA_ID=$INFURA_ID_STAGING
    ALCHEMY_ID_ETH_MAINNET=$ALCHEMY_ID_ETH_MAINNET_STAGING
    ALCHEMY_ID_ETH_GOERLI=$ALCHEMY_ID_ETH_GOERLI_STAGING
    ALCHEMY_ID_ETH_RINKEBY=$ALCHEMY_ID_ETH_RINKEBY_STAGING
    ALCHEMY_ID_ETH_ROPSTEN=$ALCHEMY_ID_ETH_ROPSTEN_STAGING
    ALCHEMY_ID_ETH_KOVAN=$ALCHEMY_ID_ETH_KOVAN_STAGING
    ALCHEMY_ID_POLYGON_MAINNET=$ALCHEMY_ID_POLYGON_MAINNET_STAGING
    ALCHEMY_ID_POLYGON_MUMBAI=$ALCHEMY_ID_POLYGON_MUMBAI_STAGING
    IPFS_SECRET=$IPFS_SECRET_STAGING
    PUBLIC_IP=$PUBLIC_IP_STAGING
    LOCAL_IP=$LOCAL_IP_STAGING
fi

if [ "$CIRCLE_BRANCH" == "master" ]; then
    TAG="stable";
    INFURA_ID=$INFURA_ID_MASTER
    ALCHEMY_ID_ETH_MAINNET=$ALCHEMY_ID_ETH_MAINNET_MASTER
    ALCHEMY_ID_ETH_GOERLI=$ALCHEMY_ID_ETH_GOERLI_MASTER
    ALCHEMY_ID_ETH_RINKEBY=$ALCHEMY_ID_ETH_RINKEBY_MASTER
    ALCHEMY_ID_ETH_ROPSTEN=$ALCHEMY_ID_ETH_ROPSTEN_MASTER
    ALCHEMY_ID_ETH_KOVAN=$ALCHEMY_ID_ETH_KOVAN_MASTER
    ALCHEMY_ID_POLYGON_MAINNET=$ALCHEMY_ID_POLYGON_MAINNET_MASTER
    ALCHEMY_ID_POLYGON_MUMBAI=$ALCHEMY_ID_POLYGON_MUMBAI_MASTER
    IPFS_SECRET=$IPFS_SECRET_MASTER
    PUBLIC_IP=$PUBLIC_IP_MASTER
    LOCAL_IP=$LOCAL_IP_MASTER
fi

for VAR_NAME in INFURA_ID ALCHEMY_ID_ETH_{MAINNET,GOERLI,RINKEBY,ROPSTEN,KOVAN} ALCHEMY_ID_POLYGON_{MAINNET,MUMBAI} AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY IPFS_SECRET NPM_TOKEN ENS_SECRET PUBLIC_IP LOCAL_IP
do
    echo "find_repace.sh: replacing $VAR_NAME"
    VAR_VAL=$(eval "echo \${$VAR_NAME}")
    # Use @ as delimiter instead of / as values may contain / but @ is unlikely
    sed -i "s@${VAR_NAME}=xxx@${VAR_NAME}=${VAR_VAL}@g" ../environments/.env.$TAG
done

cp ../environments/.env.$TAG ../environments/.env
rm ../environments/.env.secrets
