openapi: "3.0"

paths:
  /verify/etherscan:
    post:
      deprecated: true
      summary: Verify an Etherscan verified contract
      tags:
        - Stateless Verification (Deprecated)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  format: address
                  example: "0x07880D44b0f7b75464ad18fc2b980049c40A8bc3"
                chainId:
                  type: string
                  format: supported-chainId
                  example: "1"
                apiKey:
                  type: string
                  example: "*********************************"
              required:
                - address
                - chainId
          multipart/form-data:
            schema:
              type: object
              properties:
                address:
                  type: string
                  format: address
                chain:
                  type: string
                  format: supported-chainId
                apiKey:
                  type: string
                  example: "*********************************"
              required:
                - address
                - chain
      responses:
        "200":
          description: The contract has been successfully checked or sourcified
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        address:
                          type: string
                        chainId:
                          type: string
                        status:
                          type: string
                        message:
                          type: string
                        libraryMap:
                          type: object
              examples:
                Perfect Match:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "perfect"
                        libraryMap:
                          lib1: "0x3f681646d4a755815f9cb19e1acc8565a0c2ac"
                          lib2: "0x4f681646d4a755815f9cb19e1acc8565a0c2ac"
                Partial Match:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "partial"
                        libraryMap:
                          lib1: "0x3f681646d4a755815f9cb19e1acc8565a0c2ac"
                          lib2: "0x4f681646d4a755815f9cb19e1acc8565a0c2ac"
                Not Deployed:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "null"
                        message: "Chain #1 does not have a contract deployed at 0x...."
        "409":
          description: Conflict - The contract is already partially verified and the verification yieled a partial match. The files won't be saved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Already Partially Verified:
                  value:
                    error: "The contract 0x00000000219ab540356cBB839Cbe05303d7705Fa on chainId 11155111 is already partially verified. The provided new source code also yielded a partial match and will not be stored unless it's a full match"
        "429":
          description: Too Many Requests sent through Sourcify's own API key
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Etherscan API rate:
                  value:
                    error: "Etherscan API rate limit reached, try later"
                Bad Formatted Json:
                  value:
                    error: "Unexpected token ' in JSON at position 107"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Resource Missing:
                  value:
                    error: "Resource missing; unsuccessful fetching: contracts/SingleFile.sol"
                Deployed and recompiled mismatch:
                  value:
                    error: "The deployed and recompiled bytecode don't match."
