FROM node:10 as builder
WORKDIR /home/app

RUN npm install -g lerna
COPY environments/.env ./environments/
COPY services/core ./services/core
COPY services/validation ./services/validation
COPY services/verification ./services/verification
COPY src ./src
COPY scripts/run_monitor.js ./scripts/
COPY *.json ./
RUN lerna bootstrap && lerna run build

CMD ["npm", "run", "monitor:start"]
