FROM node:10-alpine as builder
WORKDIR /home/app
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh python make g++ curl
RUN npm install -g lerna
COPY environments/.env ./environments/
COPY services/core ./services/
COPY services/validation ./services/
COPY services/verification ./services/
COPY src ./src
COPY *.json ./
RUN lerna bootstrap --hoist && lerna run build

CMD ["npm", "run", "server:start"]