FROM node:10 as builder
WORKDIR /home/app

COPY environments/.env ./environments/
COPY services/core ./services/core
COPY services/validation ./services/validation
COPY services/verification ./services/verification
COPY src ./src
COPY *.json ./
RUN npx lerna bootstrap && npx lerna run build

CMD ["npm", "run", "monitor:start"]
