openapi: "3.0.0"

paths:
  /session/input-files:
    post:
      summary: Add input files
      tags:
        - Session Verification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                files:
                  type: object
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  description: This field is required
                  oneOf:
                    - type: string
                    - type: array
                      items:
                        type: string
                    - type: string
                      format: binary
                    - type: array
                      items:
                        type: string
                        format: binary
      parameters:
        - name: url
          in: query
          schema:
            type: string
            format: uri
          description: Remote file URL
          required: false
      responses:
        "200":
          description: Response is sent when the upload is successful under different conditions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  contracts:
                    type: array
                    items:
                      type: object
                      properties:
                        compiledPath:
                          type: string
                          example: "browser/1_Storage.sol"
                        name:
                          type: string
                          example: "Storage"
                        compilerVersion:
                          type: string
                          example: "0.6.6+commit.6c089d02"
                        files:
                          type: object
                          properties:
                            found:
                              type: array
                              items:
                                type: string
                            missing:
                              type: array
                              items:
                                type: string
                        verificationId:
                          type: string
                          example: "0x3f67e9f57515bb1e7195c7c5af1eff630091567c0bb65ba3dece57a56da766fe"
                        status:
                          type: string
                          enum: ["perfect", "partial", "error"]
                  unused:
                    type: array
                    items:
                      type: string
        "413":
          description: Payload Too Large
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Too much session memory used. Delete some files or clear the session."
